header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: 'base_link'
hulls:
- polygon:
    points:
    - x: 1.0
      y: 0.0
      z: 0.0
    - x: 1.0
      y: 1.0
      z: 0.0
    - x: 0.0
      y: 1.0
      z: 0.0
    - x: 0.0
      y: 0.0
      z: 0.0
  z_min: 0.2
  z_max: 2.0
- polygon:
    points:
    - x: 5.0
      y: 0.0
      z: 0.0
    - x: 7.0
      y: 0.0
      z: 0.0
    - x: 8.0
      y: 2.0
      z: 0.0
    - x: 6.0
      y: 4.0
      z: 0.0
    - x: 2.0
      y: 4.0
      z: 0.0
    - x: 0.0
      y: 4.0
      z: 0.0
    - x: 2.0
      y: 3.0
      z: 0.0
    - x: 5.0
      y: 1.0
      z: 0.0
  z_min: 0.0
  z_max: 0.5