#!/usr/bin/env python

# System
import os
import operator
import sys
import time
import datetime

# ROS
import rospy

# OpenCV
from cv_bridge import CvBridge, CvBridgeError
import cv2

# Tensorflow
import tensorflow as tf
import numpy as np

# srv
from clf_object_recognition_msgs.srv import Classify2D

# msgs
from vision_msgs.msg import Classification2D, ObjectHypothesis

# recognition
from clf_object_recognition_tensorflow import recognize


class TensorflowObjectRecognition:
    """ Performs object recognition using Tensorflow neural networks """
    def __init__(self, graph_path, labels_path, save_images_folder):
        """ Constructor
        :param graph_path: string with path + filename (incl. extension) indicating the database location
        :param labels_path: string with path + filename (incl. extension) indicating the location of the text file
        with labels etc.
        :param save_images_folder: Where to store images for debugging or data collection
        """
        # Check if the parameters are correct
        if not (os.path.isfile(graph_path) and os.path.isfile(labels_path)):
            err_msg = "DB file {} or models file {} does not exist".format(graph_path, labels_path)
            rospy.logerr(err_msg)
            sys.exit(err_msg)

        self._bridge = CvBridge()
        self._recognizer = recognize.TensorflowRecognition()
        self._classify_srv = rospy.Service('classify', Classify2D, self._classify_srv_callback)
        self._do_recognition = False  # Indicates whether a new request has been received and thus recognition must
        # be performed
        self._filename = "/tmp/tf_obj_rec.jpg"  # Temporary file name
        self._models_path = labels_path
        self._classifications = []  # List with Recognition s
        self._size = {'width': 0, 'height': 0}
        self._save_images_folder = save_images_folder
        self._bgr_image = None

        rospy.loginfo("TensorflowObjectRecognition initialized:")
        rospy.loginfo(" - graph_path=%s", graph_path)
        rospy.loginfo(" - labels_path=%s", labels_path)
        rospy.loginfo(" - save_images_folder=%s", save_images_folder)

        """1. Create a graph from saved GraphDef file """
        label_list = self._recognizer.load_graph(graph_path, labels_path)

        id_list = [str(i) for i in range(0,len(label_list))]
        id_label_dict = dict(zip(id_list, label_list))
        rospy.set_param('object_labels', id_label_dict)

    def _classify_srv_callback(self, req):
        """ Callback function for the recognize. It saves the image on a temporary location and sets _do_recognition
        to True. Subsequently, it waits until the image has been processed (i.e., until _do_recognition is False again)
        and then returns the result
        :param req: image_recognition_msgs.srv.RecognizeRequest
        :return: image_recognition_msgs.srv.RecognizeResponse
        """

        self._classifications = []

        for i in range(len(req.images)):
            try:
                self._bgr_image = self._bridge.imgmsg_to_cv2(req.images[i], "bgr8")
            except CvBridgeError as e:
                error_msg = "Could not convert to opencv image: %s" % e
                rospy.logerr(error_msg)
                raise Exception(error_msg)

            # Write the image to file
            # TODO: directly in memory, saves file operations
            cv2.imwrite(filename=self._filename, img=self._bgr_image)
            imgpath = "{}/img{}.jpg".format(self._save_images_folder, datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S_%f"))
            cv2.imwrite(filename=imgpath, img=self._bgr_image)
            size = self._bgr_image.shape[:2]  # For now, we assume the entire image is the ROI
            self._size['height'] = size[0]
            self._size['width'] = size[1]
            self._recognitions = []
            self._do_recognition = True

            # Wait until the request has been processed and return the result
            #r = rospy.Rate(1000.0)  # Not a problem to spin quickly
            if rospy.is_shutdown():
                return {"classifications": []}
            while self._do_recognition: #TODO Call self.update() directly?
                time.sleep(0.1)

        return {"classifications": self._classifications}

    def update(self):
        """ Do the actual work: if _do_recognition is True, it retrieves the saved image and tries to classify it.
        The result is stored in the _recognition member and afterwards _do_recognition is set to False. This function
        is called at a fixed frequency in the mean thread, hence NOT from the service callback. """
        if not self._do_recognition:
            return

        """2. Recognize"""
        try:
            # TODO: directly in memory, saves file operations
            sorted_result = self._recognizer.recognize(self._filename) # best score first
        except Exception as e:
            rospy.logerr("Failed to run tensorflow session: %s", e)

        classification = Classification2D()
        classification.header.stamp = rospy.Time.now()
        classification.header.frame_id = ""

        classification.results = []
        for res in reversed(sorted_result):
            hypothesis = ObjectHypothesis(id=res[0], score=res[1])
            classification.results.append(hypothesis)

        self._classifications.append(classification)

        if sorted_result:
            best_label = sorted_result[-1][0]
            best_prob = sorted_result[-1][1]

            rospy.loginfo("Best recognition result: {} with probability: {}".format(best_label, best_prob))

        self._do_recognition = False


if __name__ == '__main__':

    # Start ROS node
    rospy.init_node('clf_object_recognition')

    try:
        _graph_path = os.path.expanduser(rospy.get_param("~graph_path"))
        _labels_path = os.path.expanduser(rospy.get_param("~labels_path"))
        save_images = rospy.get_param("~save_images", True)

        save_images_folder = None
        if save_images:
            save_images_folder = os.path.expanduser(rospy.get_param("~save_images_folder", "/tmp/clf_object_recognition"))
    except KeyError as e:
        rospy.logerr("Parameter %s not found" % e)
        sys.exit(1)

    # Create object
    object_recognition = TensorflowObjectRecognition(graph_path=_graph_path,
                                                     labels_path=_labels_path,
                                                     save_images_folder=save_images_folder)

    # Start update loop
    r = rospy.Rate(100.0)
    while not rospy.is_shutdown():
        object_recognition.update()
        r.sleep()
