#!/usr/bin/env python3

# ros
import rospy
import rostopic
import rosservice

#from clf_object_recognition_3d import simple
from clf_object_recognition_3d import Image2Pcl

if __name__ == '__main__':
    rospy.init_node('detection_via_pcl')
    publish_raw_pcl = rospy.get_param('~publish_raw_pcl', True)
    publish_clean_pcl = rospy.get_param('~publish_clean_pcl', True)
    publish_detections = rospy.get_param('~publish_detections', True)
    
    detect_2d_topic = rospy.get_param('~detect_2d_topic', "/detect")

    rospy.logwarn(logger_name="detection_via_pcl", msg=("not " if not publish_detections else "")+"publishing detections")
    rospy.logwarn(logger_name="detection_via_pcl", msg=("not " if not publish_raw_pcl else "")+"publishing perceived pcl of detections")
    rospy.logwarn(logger_name="detection_via_pcl", msg=("not " if not publish_clean_pcl else "")+"publishing reference object pcl of detections")
    
    Image2Pcl.Image2Pcl(detect_2d_topic, publish_detections=publish_detections, publish_raw_pcl=publish_raw_pcl, publish_clean_pcl=publish_clean_pcl)
    
    rospy.spin()
