#!/usr/bin/env python3

# ros
import rospy
import rostopic
import rosservice

from clf_object_recognition_3d import simple

if __name__ == '__main__':
    rospy.init_node('simple_detect')
    publish_detections = rospy.get_param('~publish_detections', True)
    detect2d_topic = rospy.get_param('~detect2d_topic', "/detect")
    rospy.logwarn(logger_name="simple_3d", msg=("not " if not publish_detections else "")+"publishing detections")
    simple.SimpleDetect(detect2d_topic, publish_detections)
    rospy.spin()
